// <auto-generated />
namespace nmct.ba.cashlessproject.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initialdatabaselayout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialdatabaselayout));
        
        string IMigrationMetadata.Id
        {
            get { return "201412121617222_Initial database layout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
